name: ROS2 Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy source code to container workspace
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          ls -l /root/ros2_ws/src/mypkg/
      - name: Build ROS 2 workspace
        run: |
          source /opt/ros/humble/setup.bash
          cd /root/ros2_ws
          colcon build
      - name: Run ROS2 test
        run: |
          . /opt/ros/humble/setup.bash
          source /root/ros2_ws/install/setup.bash
          bash -xv /root/ros2_ws/src/mypkg/test/test.bash

