name: ROS2 Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pip
        run: |
          sudo apt update
          sudo apt install -y python3-pip
      - name: Build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          pip install pytz
          sudo apt install python3-pip
          pip3 install pytz
          bash -xv ./src/mypkg/test/test.bash /root
