name: ROS2 Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup ROS 2 environment
        run: |
          bash -c "source /opt/ros/humble/setup.bash"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-wheel

      - name: Copy source code to container workspace
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          ls -l /root/ros2_ws/src/mypkg/

      - name: Build ROS 2 workspace
        run: |
          source /opt/ros/humble/setup.bash
          cd /root/ros2_ws
          colcon build

      - name: Run ROS 2 test
        run: |
          source /opt/ros/humble/setup.bash
          source /root/ros2_ws/install/setup.bash
          timeout 10 ros2 launch mypkg talk_listen.launch.py | tee /tmp/mypkg.log
          cat /tmp/mypkg.log | grep 'Listen: 10'
