name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up ROS 2 workspace
        run: |
          # Clone the repository to the ROS 2 workspace
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws

          # Install ROS 2 dependencies
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r /root/ros2_ws/src/mypkg/requirements.txt || true  # 如果有依赖列表（requirements.txt）

          # Build the ROS 2 workspace
          colcon build

          # Source the ROS 2 environment and workspace setup
          . /opt/ros/foxy/setup.bash  # Use '.' instead of 'source'
          . install/setup.bash  # Use '.' instead of 'source'

      - name: Run tests
        run: |
          # Source the ROS 2 setup files again to ensure environment is set
          . /opt/ros/foxy/setup.bash  # Use '.' instead of 'source'
          . install/setup.bash  # Use '.' instead of 'source'

          # Run the test bash script
          bash -xv /root/ros2_ws/src/mypkg/test/test.bash /root
          
      - name: Clean up
        run: |
          # Optionally stop running processes or clean up
          pkill -f talker
          pkill -f listener
